image: "ruby:2.5.1"

services:
  - postgres:latest

variables:
  POSTGRES_DB: database_name

cache:
  paths:
    - vendor/ruby

stages:
  - static_code_analysis
  - test
  - deploy

before_script:
  - ruby -v 
  - apt-get update -q && apt-get install nodejs -yqq
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor

rubocop:
  stage: static_code_analysis
  script:
  - bundle exec rubocop
  only:
  - branches

rspec:
  stage: test
  script:
  - bundle exec rspec

deploy_staging:
  stage: deploy
  type: deploy
  environment: staging
  script:
  - gem install dpl
  - dpl --provider=heroku --app=omae-app-staging --api-key=$HEROKU_PRODUCTION_KEY
  only:
  - develop


deploy:
  stage: deploy
  environment: production
  script:
  - gem install dpl
  - dpl --provider=heroku --app=omae-app --api-key=$HEROKU_PRODUCTION_KEY
  only:
  - master
